apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-oc-items-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /data/app-oc-items-mysql
    server: 10.16.76.223 
  persistentVolumeReclaimPolicy: Retain